---
  - name: SO FAMILY REDHAT
    include_tasks: /etc/ansible/roles/uxxi_sstt_ldap/src/roles/linux-ldap-enroll/tasks/redhat.yml
    when: ansible_os_family == 'RedHat'

  - name: SO FAMILY UBUNTU
    include_tasks: /etc/ansible/roles/uxxi_sstt_ldap/src/roles/linux-ldap-enroll/tasks/ubuntu.yml
    when: ansible_os_family == 'Debian'

  #- name: SO FAMILY REDHAT6
  #  include_tasks: /etc/ansible/roles/uxxi_sstt_ldap/src/roles/linux-ldap-enroll/tasks/vers6.yml.yml
  #  when: ansible_os_family == 'RedHat' and ansible_distribution_version == '5'
